WEAPON_CONFIG = {
    "Fireball" : {
        "type" : "ranged",
        "damage" : 5,
        "speed" : 300,
        "cooldown" : 1.0,
        "projectile_count" : 2,
        "sprite_path" : "src/assets/items/weapons/fireball.png",
        "animation" : {
            "sprite_width" : 32,
            "sprite_height": 22,
            "start_row" : 0,
            "start_frames": 4,
            "animation_speed" : 0.1,
        },
        "special" : {
            "lifetime" : 3.0,
        },
        "shop": {
            "price": 10,
            "max_level": 5,
            "evolution_to": None,
        },
    },
    "Sword" : {
        "type" : "mele",
        "damage" : 3,
        "cooldown" : 1,
        "speed" : 0,
        "projectile_count" : 3,
        "sprite_path" : "src/assets/items/weapons/sword.png",
        "animation" : {
            "sprite_height": 191,
            "start_row" : 0,
            "start_frames": 3,
            "animation_speed" : 0.1,
            "sprite_width" : 254,
        },
        "special" : {
            "attack_duration" : 0.3,
            "attack_radius" : 80,
        },
        "shop": {
            "price": 10,
            "max_level": 5,
            "evolution_to": None,
        },
    },
    "Boomerang" : {
        "type" : "ranged",
        "damage" : 2,
        "speed" : 400,
        "cooldown" : 1.5,
        "projectile_count" : 3,
        "sprite_path" : "src/assets/items/weapons/boomerang.png",
        "animation" : {
            "sprite_width" : 32,
            "sprite_height": 32,
            "start_row" : 0,
            "start_frames": 4,
            "animation_speed" : 0.05,
        },
        "special" : {
            "pierce_count" : 3,
            "return_speed" : 450,
            "lifetime" : 1.8,
        },
        "shop": {
            "price": 10,
            "max_level": 5,
            "evolution_to": None,
        },
    },
    "Spear" : {
        "type" : "mele",
        "damage" : 4,
        "speed" : 0,
        "cooldown" : 1.2,
        "projectile_count" : 1,
        "sprite_path" : "src/assets/items/weapons/spear.png",
        "animation" : {
            "sprite_width" : 128,
            "sprite_height": 96,
            "start_row" : 0,
            "start_frames": 1,
            "animation_speed" : 0.05,
        },
        "special" : {
            "attack_duration" : 0.6,
            "attack_range" : 140,
            "hit_cooldown" : 0.6,
            "hitbox_width" : 26,
            "hitbox_length" : 52,
        },
        "shop": {
            "price": 10,
            "max_level": 5,
            "evolution_to": None,
        },
    },
    "Typhoon" : {
        "type" : "mele",
        "damage" : 4,
        "speed" : 0,
        "cooldown" : 1.0,
        "projectile_count" : 1,
        "sprite_path" : "src/assets/items/weapons/sun.png",
        "animation" : {
            "sprite_width" : 192,
            "sprite_height": 192,
            "start_row" : 0,
            "start_frames": 4,
            "animation_speed" : 0.1,
        },
        "special" : {
            "attack_duration" : 1.0,
            "hit_cooldown" : 0.25,
        },
        "shop": {
            "price": 10,
            "max_level": 5,
            "evolution_to": None,
        },
    },
    "Meteor" : {
        "type" : "ranged",
        "damage" : 6,
        "speed" : 0,
        "cooldown" : 3.0,
        "projectile_count" : 2,
        "range" : 500,
        "sprite_path" : "src/assets/items/weapons/meteor.png",
        "animation" : {
            "sprite_width" : 96,
            "sprite_height": 96,
            "start_row" : 0,
            "start_frames": 4,
            "animation_speed" : 0.1,
        },
        "special" : {
            "attack_duration" : 0.4,
            "hit_cooldown" : 0.3,
            "scatter_factor" : 0.1,
            "min_scatter" : 12,
            "max_scatter" : 48,
        },
        "shop": {
            "price": 10,
            "max_level": 5,
            "evolution_to": None,
        },
    },
}